import numpy as np
arr_1=np.array([[10,20],[30,40]])
arr_2=np.array([[20,10],[40,30]])
print("matrix addition")
print(np.add(arr_1,arr_2))
print("matrix subtraction")
print(np.subtract(arr_1,arr_2))
print("matrix division")
print(np.divide(arr_1,arr_2))
print("matrix multipication")
print(np.multiply(arr_1,arr_2))
print("matrix subtraction")
print(np.dot(arr_1,arr_2))
print("matrix Transpose")
print(arr_1.transpose())
print("sum of digonal elements")
print(np.trace(arr_1))
